ExamSystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('exam.urls')),
    url(r'^api/v1/exam/', include('exam.api_urls')),
]

exam/urls.py
from django.conf.urls import url, include

from exam import views

urlpatterns = [
    url(r'^$', views.login, name="login"),
    url(r'^logout/$', views.user_logout, name="logout"),
    url(r'^dashboard/$', views.dashboard, name="dashboard"),
    url(r'^dashboard/(?P<id>.*)/$', views.update_speciality, name="update_speciality"),
    url(r'^speciality/$', views.create_speciality, name="speciality"),
    url(r'^question/$', views.create_question, name="question"),
    url(r'^question/list$', views.question_list, name="question_list"),
    url(r'^topics/$', views.create_topic, name="topics"),
    url(r'^topics/list/$', views.topic_list, name="topics_list"),
    url(r'^create_newuser/$', views.create_newuser, name="create_newuser"),
    url(r'^teacher/list/$', views.user_list, name="teacher_list"),
    url(r'^distribution/$', views.distributionview, name="distribution"),
    url(r'^generate/$', views.generate_exam, name="generate_question"),
    url(r'^select_topics/$', views.selecttopics, name="select_topics"),
]

exam/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Speciality(models.Model):
    name = models.CharField(max_length=45, blank=True)
    create_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Topics(models.Model):
    name = models.CharField(max_length=45, blank=True)
    speciality = models.ForeignKey(Speciality, blank=True)
    create_date = models.DateTimeField(auto_now=True)
    user = models.IntegerField(default=1)

    def __str__(self):
        return self.name


class Question(models.Model):
    name = models.CharField(max_length=45, blank=True)

    def __str__(self):
        return self.name


class Answer(models.Model):
    qstion = models.CharField(max_length=45, blank=True)
    answr = models.CharField(max_length=45, blank=True)
    question = models.ForeignKey(Question, blank=True)

    def __str__(self):
        return self.qstion


class Journal(models.Model):
    name = models.CharField(max_length=45, null=True, blank=True)
    topics = models.ForeignKey(Topics)
    create_date = models.DateTimeField(auto_now=True)
    user = models.IntegerField(default=1)

    def __str__(self):
       return str(self.pk)


class JournalTransaction(models.Model):
    qstion = models.CharField(max_length=45, blank=True)
    answr = models.CharField(max_length=45, blank=True)
    journal = models.ForeignKey(Journal, blank=True, on_delete=models.CASCADE, related_name="journal_transactions")
    create_date = models.DateTimeField(auto_now=True)

    def __str__(self):
       # return 'journaltransactionstr'
        return self.qstion

class Distribution(models.Model):
    user = models.ForeignKey(User)
    speciality = models.ForeignKey(Speciality, default=1)
    create_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.topics

exam/forms.py
from django import forms

from exam.models import Speciality, Topics, Answer, Question, Distribution


class SpecialityForm(forms.ModelForm):
    class Meta:
        model = Speciality
        fields = '__all__'


class TopicsForm(forms.ModelForm):
    class Meta:
        model = Topics
        fields = '__all__'


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = '__all__'


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = '__all__'


class DistributionForm(forms.ModelForm):
    class Meta:
        model = Distribution
        fields = '__all__'

exam/views.py
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
# Create your views here.
from exam.forms import SpecialityForm, TopicsForm, DistributionForm
from exam.models import Speciality, Topics, Journal, JournalTransaction
from django.contrib import messages
from django.contrib.auth.models import User

# =========================== LOG IN & LOG OUT AREA ========================== #


def login(request):
    """
    User Login area
    :param request:
    :return: Dashboard
    """
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                auth_login(request, user)
                return HttpResponseRedirect('dashboard')
            else:
                return HttpResponse("Your account is disabled.")
        else:
            print "Invalid login details: {0}, {1}".format(username, password)
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'login.html')


@login_required
def user_logout(request):
    """
     User Logout
    :param request:
    :return: Login page
    """
    logout(request)
    return HttpResponse("Successfully Logout")


# =========================== SPECIALITY ===================================== #
@login_required
def create_speciality(request):
    """
    Create Speciality
    :param request:
    :return:
    """
    if request.method == 'POST':
        form = SpecialityForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            form = SpecialityForm()
            messages.success(request, 'Form submission successful')
    else:
        form = SpecialityForm()
    return render(request, 'create_speciality.html', {'form': form})


@login_required
def dashboard(request):
    """
    Show all the Speciality as a list view
    :param request:
    :return: Speciality list
    """
    if request.user.is_superuser:
        queryset = Speciality.objects.all()
    else:
        queryset = Speciality.objects.filter(distribution__user__username=request.user.username)
    context = {
        "object_list": queryset
    }
    return render(request, 'dashboard.html', context)


def update_speciality(request, id):
    if request.method == "GET":
        speciality = Speciality.objects.get(id=id)
    if request.method == "POST":
        name = request.POST.get('name')
        print (name)
        id = request.POST.get('id')
        speciality = Speciality.objects.filter(id=id)
        speciality.name = name
        speciality.save()

    context = {
        "speciality": speciality
    }
    return render(request, 'update_speciality.html', context)


# =========================== QUESTIONS ===================================== #
@login_required
def create_question(request):
    """
    Create Questions with multiple options
    :param request:
    :return:
    """
    queryset = Topics.objects.filter(user=request.user.id)
    return render(request, 'create_question.html', {'obj_list': queryset})


@login_required
def question_list(request):
    """
    Show the questions list
    :param request:
    :return:
    """
    queryset = Journal.objects.filter(user=request.user.id)
    context = {
        "object_list": queryset
    }
    return render(request, 'list_questions.html', context)


# =========================== TOPICS ===================================== #
@login_required
def create_topic(request):
    """
    Create question under specific Speciality
    :param request:
    :return:
    """
    special = Speciality.objects.filter(distribution__user__username=request.user.username)
    if request.method == 'POST':
        form = TopicsForm(request.POST)
        if form.is_valid():
            print ("I am here One")
            instance = form.save(commit=False)
            instance.save()
            print ("I am here One")
            form = TopicsForm()
            print ("I am here One")
            messages.success(request, 'Form Submission Successful')
    else:
        form = TopicsForm()
    context = {
        "form": form,
        "special": special
    }
    return render(request, 'create_topics.html', context)


@login_required
def topic_list(request):
    """
    Show the Topics List
    :param request:
    :return:
    """
    if request.user.is_superuser:
        queryset = Topics.objects.all()
    else:
        queryset = Topics.objects.filter(user=request.user.id)
    context = {
        "object_list": queryset
    }
    return render(request, 'list_topics.html', context)


# =========================== NEW USERS ===================================== #
@login_required
def create_newuser(request):
    """
    Create New User
    :param request:
    :return:
    """
    if request.method == 'POST':
        username = request.POST.get("username", None)
        email = request.POST.get("email", None)
        password = request.POST.get("password", None)
        first_name = request.POST.get("first_name", None)
        last_name = request.POST.get("last_name", None)

        user, created = User.objects.get_or_create(username=username, email=email)
        if created:
            user.set_password(password)  # This line will hash the password
            user.first_name = first_name
            user.last_name = last_name

            user.save()  # DO NOT FORGET THIS LINE

        print (username, email, password, first_name, last_name)
    return render(request, 'create_user.html')


@login_required
def user_list(request):
    """
    Show the User List
    :param request:
    :return:
    """
    queryset = User.objects.all()
    context = {
        "object_list": queryset
    }
    return render(request, 'list_user.html', context)


# =========================== DISTRIBUTIONS ===================================== #
@login_required
def distributionview(request):
    """
    Distribute user to specific speciality
    :param request:
    :return:
    """
    form = DistributionForm()
    if request.method == 'POST':
        form = DistributionForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            form = DistributionForm()
            messages.success(request, 'Form submission successful')
    return render(request, 'distribution.html', {'form': form})


# =========================== QUESTIONS GENERATIONS ===================================== #
def generate_exam(request):
    """
    Admin can Generate the questions
    :param request:
    :return:
    """
    # queryset = JournalTransaction.objects.filter(journal__topics=13)
    topicsno = request.POST.get("topicsno", None)
    limitno = request.POST.get("limitno", None)
    queryset = Journal.objects.filter(topics=topicsno)[0:limitno]
    context = {
        "object_list": queryset
    }
    return render(request, 'generate_exam.html', context)


def selecttopics(request):
    """
    Generate question need select the specific category and the question number
    :param request:
    :return:
    """
    queryset = Topics.objects.all()
    context = {
        "object_list": queryset
    }
    return render(request, 'select_topics.html', context)

exam/templates/create_question.html
{% extends 'base.html' %}
{% block title %} Create Question{% endblock title %}
{% block content %}
<br><br>
<div class="portlet box yellow">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Add New Question</div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <form method="POST" action="" id="id_form" data-toggle="validator" role="form">{% csrf_token %}
        <input type="hidden" name="user" value="{{ request.user.id }}">
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">Topic Name: </label>
                    <div class="col-md-8">
                        <select name="topics" class="form-control">
                            <option value="">---------</option>
                            {% for obj in obj_list %}
                            <option value="{{ obj.id }}">{{ obj.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Question: </label>
                    <div class="col-md-8">
                        <input type="text" name="name" class="form-control" placeholder="Enter text">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-3 control-label">Answer: </label>
                    <div class="col-md-7">
                        <input type="text" name="journal_transactions[0][qstion]" class="form-control" placeholder="Enter text">
                    </div>
                    <div class="col-md-1">
                        <input type="text" name="journal_transactions[0][answr]" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Answer: </label>
                    <div class="col-md-7">
                        <input type="text" name="journal_transactions[1][qstion]" class="form-control" placeholder="Enter text">
                    </div>
                    <div class="col-md-1">
                        <input type="text" name="journal_transactions[1][answr]" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Answer: </label>
                    <div class="col-md-7">
                        <input type="text" name="journal_transactions[2][qstion]" class="form-control" placeholder="Enter text">
                    </div>
                    <div class="col-md-1">
                        <input type="text" name="journal_transactions[2][answr]" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Answer: </label>
                    <div class="col-md-7">
                        <input type="text" name="journal_transactions[3][qstion]" class="form-control" placeholder="Enter text">
                    </div>
                    <div class="col-md-1">
                        <input type="text" name="journal_transactions[3][answr]" class="form-control">
                    </div>
                </div>
            <table>
                <tbody class="input_fields_wrap inputdeletebutton" id="dynamicInput">
                </tbody>
            </table>
                <a class="btn bg-navy btn-flat margin" onClick="addInput('dynamicInput')">Add New Field </a>



            </div>
            <div class="form-actions fluid">
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn green">Save</button>
                        <button type="button" class="btn default">Reset</button>
                    </div>
                </div>
            </div>
        </form>
        <!-- END FORM-->
    </div>
</div>

    <script>
        var counter = 3;
        var limit = 10;
        function addInput(divName){
             if (counter == limit)  {
                  alert("You have reached the limit of adding " + counter + " inputs");
             }
             else {
                 var newdiv = document.createElement('tr');
                 newdiv.innerHTML = '<td style="width: 100%;"><div class="form-group"><label class="col-md-3 control-label" style="margin-right: 11px ! important;">Answer:</label><div class="col-md-7"><input type="text" name="journal_transactions[' + (counter + 1) + '][qstion]" class="form-control" placeholder="Enter text"></div><div class="col-md-1"><input type="text" name="journal_transactions[' + (counter + 1) + '][answr]" class="form-control"></div></div><td><a href="javascript:void(0);" onClick="this.parentNode.parentNode.parentNode.removeChild(this.parentNode.parentNode);" >Delete</a></td>';
                 document.getElementById(divName).appendChild(newdiv);
                 counter++;
             }}

            $(document).ready(function () {
            $("#id_form").submit(function (event) {
                event.preventDefault();
                var formData = $(this).serializeJSON();
                console.log(formData);
                $.ajax({
                    url: "{% url "cheque_receive" %}",
                    type: "POST",
                    data: formData,
                    contentType: "application/json",
                    Accept: "application/json",
                    success: function (data) {
                        document.getElementById("id_form").reset();
                        toastr.success("Insertion successful");
                        setTimeout(function(){// wait for 5 secs(2)
                               location.reload(); // then reload the page.(3)
                          }, 1000);
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        toastr['error']('Error occured');
                    }
                });
            });
        });
    </script>
{% endblock content %}

exam/templates/create_speciality.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %} Create Question{% endblock title %}
{% block content %}
<br><br>
<div class="portlet box yellow">
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Add New Speciality</div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <form action="{% url 'speciality' %}" class="form-horizontal" method="POST">
            {% csrf_token %}
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">Speciality Name: </label>
                    <div class="col-md-8">
                        {{ form.name|add_class:"form-control" }}
                    </div>
                </div>
            </div>
            <div class="form-actions fluid">
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn green">Save</button>
                        <button type="button" class="btn default">Reset</button>
                    </div>
                </div>
            </div>
        </form>
        <!-- END FORM-->
    </div>
</div>
{% endblock content %}

exam/templates/create_topics.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %} Create Question{% endblock title %}
{% block content %}
<br><br>
<div class="portlet box yellow">
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Add New Topics</div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <form action="{% url 'topics' %}" class="form-horizontal" method="POST">
            {% csrf_token %}
            <input type="hidden" name="user" value="{{ request.user.id }}">
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">Speciality Name: </label>
                    <div class="col-md-8">
                        <select name="speciality" id="id_speciality" class="form-control">
                            <option value="">--------</option>
                            {% for obj in special %}
                                <option value="{{ obj.id }}">{{ obj.name }}</option>
                            {% endfor %}
                        </select>
{#                        {{ form.speciality|add_class:"form-control" }}#}
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Topic Name: </label>
                    <div class="col-md-8">
                        {{ form.name|add_class:"form-control" }}
                    </div>
                </div>
            </div>
            <div class="form-actions fluid">
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn green">Save</button>
                        <button type="button" class="btn default" onclick="window.location.reload()">Reset</button>
                    </div>
                </div>
            </div>
        </form>
        <!-- END FORM-->
    </div>
</div>
{% endblock content %}

exam/templates/create_user.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %} Create New User{% endblock title %}
{% block content %}
<br><br>
<div class="portlet box yellow">
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Create New User</div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <form action="" class="form-horizontal" method="POST">
            {% csrf_token %}
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">UserName: </label>
                    <div class="col-md-8">
                        <input type="text" name="username" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Email Address: </label>
                    <div class="col-md-8">
                       <input type="text" name="email" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">PassWord: </label>
                    <div class="col-md-8">
                       <input type="text" name="password" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">First Name: </label>
                    <div class="col-md-8">
                       <input type="text" name="first_name" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Last Name: </label>
                    <div class="col-md-8">
                       <input type="text" name="last_name" class="form-control">
                    </div>
                </div>


            </div>
            <div class="form-actions fluid">
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn green">Save</button>
                        <button type="button" class="btn default" onclick="window.location.reload()">Reset</button>
                    </div>
                </div>
            </div>
        </form>
        <!-- END FORM-->
    </div>
</div>
{% endblock content %}

exam/templates/dashboard.html
{% extends 'base.html' %}
{% block title %} Dashboard{% endblock title %}
{% block content %}
<div class="portlet light bordered">
    <div class="portlet-title">
        <div class="caption font-dark">
            <i class="icon-settings font-dark"></i>
            <span class="caption-subject bold uppercase">List of Speciality</span>
        </div>
        <div class="tools"> </div>
    </div>
    <div class="portlet-body">
        <table class="table table-striped table-bordered table-hover" id="sample_1">
            <thead>
                <tr>
                    <th> ID # </th>
                    <th> Speciality </th>
                    <th> Created On </th>
                    <th> Action </th>
                </tr>
            </thead>
            <tbody>
                {% for obj in object_list %}
                <tr>
                    <td> {{ forloop.counter }} </td>
                    <td> {{ obj.name }} </td>
                    <td> {{ obj.create_date }} </td>
                    <td><a href="{{ obj.id }}">Update</a> </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

exam/templates/distribution.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %} Create New User{% endblock title %}
{% block content %}
<br><br>
<div class="portlet box yellow">
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Create New User</div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <form action="" class="form-horizontal" method="POST">
            {% csrf_token %}
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">UserName: </label>
                    <div class="col-md-8">
                        {{ form.user|add_class:"form-control" }}
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Topics Name </label>
                    <div class="col-md-8">
                       {{ form.speciality|add_class:"form-control" }}
                    </div>
                </div>

            </div>
            <div class="form-actions fluid">
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn green">Save</button>
                        <button type="button" class="btn default" onclick="window.location.reload()">Reset</button>
                    </div>
                </div>
            </div>
        </form>
        <!-- END FORM-->
    </div>
</div>
{% endblock content %}

exam/templates/list_topics.html
{% extends 'base.html' %}
{% block title %} List of Topics {% endblock title %}
{% block content %}
<div class="portlet light bordered">
    <div class="portlet-title">
        <div class="caption font-dark">
            <i class="icon-settings font-dark"></i>
            <span class="caption-subject bold uppercase">List of Topics</span>
        </div>
        <div class="tools"> </div>
    </div>
    <div class="portlet-body">
        <table class="table table-striped table-bordered table-hover" id="sample_1">
            <thead>
                <tr>
                    <th> ID # </th>
                    <th> Topics Name </th>
                    <th> No. of Question </th>
                    <th> Speciality </th>
                    <th> Created On </th>
{#                    <th> Action </th>#}
                </tr>
            </thead>
            <tbody>
                {% for obj in object_list %}
                <tr>
                    <td> {{ forloop.counter }} </td>
                    <td> {{ obj.name }} </td>
                    <td> {{ obj.journal_set.count }} </td>
                    <td> {{ obj.speciality }} </td>
                    <td> {{ obj.create_date }} </td>
{#                    <td> Win 95+ </td>#}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

exam/templates/select_topics.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %} Create Question{% endblock title %}
{% block content %}
<br><br>
<div class="portlet box yellow">
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Select Topic for Question Generate</div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <form action="{% url 'generate_question' %}" class="form-horizontal" method="POST">
            {% csrf_token %}
            <input type="hidden" name="user" value="{{ request.user.id }}">
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">Topic Name: </label>
                    <div class="col-md-8">
                        <select name="topicsno" id="id_speciality" class="form-control">
                            <option value="">--------</option>
                            {% for obj in object_list %}
                                <option value="{{ obj.id }}">{{ obj.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Write the number of Question: </label>
                    <div class="col-md-8">
                        <input type="text" name="limitno" class="form-control">
                    </div>
                </div>
            </div>
            <div class="form-actions fluid">
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn green">Generate Question</button>
                        <button type="button" class="btn default" onclick="window.location.reload()">Reset</button>
                    </div>
                </div>
            </div>
        </form>
        <!-- END FORM-->
    </div>
</div>
{% endblock content %}